name: spotify_clone
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.0
  http: ^1.2.1
  fpdart: ^1.1.0
  shared_preferences: ^2.2.3
  dotted_border: ^2.1.0
  flex_color_picker: ^3.5.1
  file_picker: ^8.0.6
  audio_waveforms: ^1.0.5
  just_audio: ^0.9.39

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
